### ISSUE TITLE
Entries are Doubled

### ISSUE THREAD

**Issue by alexhollinghead** [NicNol/course-analytics#60]
The entries are showing up twice for some reason on several pages. For example:
https://www.osu-cs-ca.com/courses/CS-340

**Comment by NicNol** [comment]
Thank you for letting me know. I confirmed that entries were doubled. I did a reset locally and can see that the entries are back to normal now, but will try to monitor to see if any errors occur with the automated scraping of the results spreadsheet. The scraping occurs hourly, so I should have a few data points tonight and more in the morning.
