### ISSUE TITLE
Please add new class CS 374

### ISSUE THREAD

**Issue by 6dayspizza** [NicNol/course-analytics#93]
Hi! Former class CS 344 has been revamped significantly. All the current reviews are thus painting an outdated perception of the course workload. As the class name has also changed last year, I suggest adding a new class "CS 374" and rename the old one "CS 344 (until winter 2024)". This allows for new reviews and a new summary of the workload?

**Comment by NicNol** [comment]
Hello @6dayspizza ! Thanks for raising an issue.

Right now the course reviews map to the [Google Survey](https://docs.google.com/forms/d/e/1FAIpQLSeAWZa_OWYqwOte5yw4loGgE6hEUqOJOeSpmzStZF_HcufufQ/viewform). I do some [additional formatting on the names](https://github.com/NicNol/course-analytics/blob/main/scraper/src/scheduler/helper/summarize.ts#L109-L152) based on current and historical names for the courses. You can see an example of a course number that was changed for CS 467.

I can:

- change the presentation of "CS 344" to be "CS 374" and combine data for both, or
- I can keep CS 344 and create a new page for CS 374, keeping the data separate.

It looks like you're requesting the second option. I'm okay with either approach to be honest.

I've also reached out to the owner of the Google Survey to update the course number from 344 to 374. I will be blocked on making any progress until the survey is updated. Once the survey is updated, the change in this repo should be relatively simple.

**Comment by 6dayspizza** [comment]
Hi @NicNol , thanks for your quick reply! I would suggest going with option 2, that way the reviews can be reset, and at the same time, students still have the option to look at the reviews from the previous class (344) if they want to. I have also reached out to the owner of the Course Explorer, but have not heard back. I assume they are also the owner of the Google Survey. I hope they are still active.

**Comment by NicNol** [comment]
The Google Survey is now updated and I have added CS 374 to the repo's class list. As an aside, the Google Survey is not owned by the maintainer of the Course Explorer repo, but by one of the subreddit mods.

I believe the existing code will now accommodate option 2. If you or anyone you know has taken CS 374, they can submit a course review. The service that scrapes the survey results runs hourly around the XX:45 minute mark and will pick up the reviews. The app caches each page for an hour and may show a stale page while it's rebuilding a new page. Hopefully we can test that it's working once we have a review submitted.

**Comment by NicNol** [comment]
I'm seeing CS374 in the class list, so I'm going to close this issue now. Thanks for raising it!
